#!/usr/bin/env python3
"""
Export BSH 2026 Interactive Map Tour data to a well-organized Word document.

Usage:
    node export_tour_data.js > tour_data.json
    python3 export_tours_to_word.py

Reads tour_data.json (generated by export_tour_data.js) and produces
BSH_2026_Tour_Content.docx — ready for track-changes editing.
"""

import json
import re
import os
import subprocess
import tempfile
from html.parser import HTMLParser

try:
    from docx import Document
    from docx.shared import Pt, Cm, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.table import WD_TABLE_ALIGNMENT
    HAVE_DOCX = True
except ModuleNotFoundError:
    HAVE_DOCX = False


# ── HTML → structured blocks parser ──────────────────────────────────

class HTMLToBlocks(HTMLParser):
    """Convert HTML content into a list of structured blocks for Word output."""

    def __init__(self):
        super().__init__()
        self.blocks = []
        self._current_text = ""
        self._current_parts = []
        self._current_bold = False
        self._in_li = False
        self._li_text = ""
        self._li_parts = []
        self._ul_items = []
        self._in_ul = False
        self._in_h4 = False
        self._h4_text = ""

    def handle_starttag(self, tag, attrs):
        if tag == "p":
            self._current_text = ""
            self._current_parts = []
            self._current_bold = False
        elif tag == "strong":
            if self._in_li:
                if self._li_text:
                    self._li_parts.append((self._li_text, False))
                    self._li_text = ""
            else:
                if self._current_text:
                    self._current_parts.append((self._current_text, False))
                    self._current_text = ""
            self._current_bold = True
        elif tag == "ul":
            self._in_ul = True
            self._ul_items = []
        elif tag == "li":
            self._in_li = True
            self._li_text = ""
            self._li_parts = []
        elif tag == "h4":
            self._in_h4 = True
            self._h4_text = ""

    def handle_endtag(self, tag):
        if tag == "p":
            if self._current_text:
                self._current_parts.append((self._current_text, False))
                self._current_text = ""
            if self._current_parts:
                self.blocks.append({"type": "paragraph", "parts": self._current_parts})
                self._current_parts = []
        elif tag == "strong":
            if self._in_li:
                if self._li_text:
                    self._li_parts.append((self._li_text, True))
                    self._li_text = ""
            else:
                if self._current_text:
                    self._current_parts.append((self._current_text, True))
                    self._current_text = ""
            self._current_bold = False
        elif tag == "li":
            if self._li_text:
                self._li_parts.append((self._li_text, False))
            self._ul_items.append(self._li_parts)
            self._in_li = False
            self._li_text = ""
            self._li_parts = []
        elif tag == "ul":
            self._in_ul = False
            if self._ul_items:
                self.blocks.append({"type": "list", "items": self._ul_items})
                self._ul_items = []
        elif tag == "h4":
            self._in_h4 = False
            if self._h4_text.strip():
                self.blocks.append({"type": "subheading", "text": self._h4_text.strip()})
            self._h4_text = ""

    def handle_data(self, data):
        if self._in_h4:
            self._h4_text += data
        elif self._in_li:
            self._li_text += data
        else:
            self._current_text += data


def html_to_blocks(html_string):
    parser = HTMLToBlocks()
    parser.feed(html_string)
    return parser.blocks


# ── RTF fallback helpers ─────────────────────────────────────────────

def rtf_escape(text):
    escaped = []
    for char in text:
        codepoint = ord(char)
        if char == "\\":
            escaped.append(r"\\")
        elif char == "{":
            escaped.append(r"\{")
        elif char == "}":
            escaped.append(r"\}")
        elif char == "\n":
            escaped.append(r"\line ")
        elif codepoint > 127:
            if codepoint > 32767:
                codepoint -= 65536
            escaped.append(fr"\u{codepoint}?")
        else:
            escaped.append(char)
    return "".join(escaped)


def rtf_run(text, *, bold=False, italic=False, color=None, size=None):
    if not text:
        return ""
    prefixes = []
    suffixes = []
    if bold:
        prefixes.append(r"\b ")
        suffixes.append(r"\b0 ")
    if italic:
        prefixes.append(r"\i ")
        suffixes.append(r"\i0 ")
    if color is not None:
        prefixes.append(f"\\cf{color} ")
        suffixes.append(r"\cf0 ")
    if size is not None:
        prefixes.append(f"\\fs{size} ")
    return "".join(prefixes) + rtf_escape(text) + "".join(reversed(suffixes))


def rtf_paragraph(runs, *, align="left", indent=0, first_indent=0, space_after=120):
    align_code = {"left": r"\ql", "center": r"\qc", "right": r"\qr"}.get(align, r"\ql")
    pieces = [r"\pard", align_code, f"\\li{indent}", f"\\fi{first_indent}", f"\\sa{space_after}", " "]
    pieces.extend(runs)
    pieces.append(r"\par")
    return "".join(pieces)


def write_rtf_as_docx(rtf_text, output_path):
    with tempfile.NamedTemporaryFile("w", suffix=".rtf", delete=False, encoding="utf-8") as tmp:
        tmp.write(rtf_text)
        tmp_path = tmp.name
    try:
        subprocess.run(
            ["textutil", "-convert", "docx", "-output", output_path, tmp_path],
            check=True,
        )
    finally:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)


def build_document_rtf(tours, output_path):
    parts = [
        r"{\rtf1\ansi\deff0",
        r"{\fonttbl{\f0 Calibri;}}",
        r"{\colortbl;\red51\green51\blue51;\red85\green85\blue85;\red102\green102\blue102;\red68\green102\blue170;}",
        "\n",
    ]

    parts.append(rtf_paragraph([rtf_run("BSH 2026 Interactive Map Tour", bold=True, size=34)], align="center", space_after=80))
    parts.append(rtf_paragraph([rtf_run("Non-Profit Housing in Vancouver", color=2, size=26)], align="center", space_after=80))
    parts.append(rtf_paragraph([rtf_run("Tour Content for Editorial Review", italic=True, color=3, size=22)], align="center", space_after=240))

    parts.append(rtf_paragraph([rtf_run("Table of Contents", bold=True, size=28)], space_after=180))
    for tour in tours:
        parts.append(rtf_paragraph([rtf_run(tour["title"], bold=True, size=24)], space_after=40))
        if tour.get("description"):
            parts.append(rtf_paragraph([rtf_run(tour["description"], italic=True, color=3, size=20)], indent=360, space_after=80))
        for idx, stop in enumerate(tour["stops"], 1):
            parts.append(rtf_paragraph([
                rtf_run(f"{idx}. ", bold=True),
                rtf_run(stop["title"], bold=True),
                rtf_run(f" — {stop['location']}", color=2),
            ], indent=360, first_indent=-180, space_after=40))

    parts.append(r"\page")

    for tour_idx, tour in enumerate(tours):
        parts.append(rtf_paragraph([rtf_run(tour["title"], bold=True, size=30)], space_after=120))
        if tour.get("description"):
            parts.append(rtf_paragraph([rtf_run(tour["description"], italic=True, color=2, size=22)], space_after=180))

        for stop_idx, stop in enumerate(tour["stops"], 1):
            parts.append(rtf_paragraph([rtf_run(f"Stop {stop_idx}: {stop['title']}", bold=True, size=28)], space_after=80))
            parts.append(rtf_paragraph([rtf_run(f"Location: {stop['location']}", italic=True, color=2)], space_after=80))

            if stop.get("stats"):
                stats_text = " | ".join(f"{stat['label']}: {stat['value']}" for stat in stop["stats"])
                parts.append(rtf_paragraph([
                    rtf_run("Quick Facts: ", bold=True),
                    rtf_run(stats_text),
                ], space_after=120))

            for section in stop.get("sections", []):
                section_type = section.get("type")
                section_id = section.get("id", "")
                section_label = section.get("label", "")

                if section_type == "gallery":
                    continue

                if section_id == "overview":
                    heading = "Overview"
                elif section_id == "highlights":
                    heading = "At This Stop"
                elif section_id == "details":
                    heading = section_label
                elif section_type == "resources":
                    heading = "Resources"
                else:
                    heading = section_label or section_id.title()

                parts.append(rtf_paragraph([rtf_run(heading, bold=True, size=24)], space_after=60))

                if section_type == "highlights":
                    for hi_idx, hi in enumerate(section.get("highlights", []), 1):
                        runs = [
                            rtf_run(f"{hi_idx}. ", bold=True),
                            rtf_run(hi["title"], bold=True),
                        ]
                        if hi.get("meta"):
                            runs.append(rtf_run(f" [{hi['meta']}]", color=2, size=18))
                        parts.append(rtf_paragraph(runs, indent=180, space_after=20))
                        parts.append(rtf_paragraph([rtf_run(hi["description"])], indent=540, space_after=80))

                elif section_type == "resources":
                    for res in section.get("resources", []):
                        parts.append(rtf_paragraph([rtf_run(f"• {res['title']}", bold=True)], indent=180, first_indent=-180, space_after=20))
                        if res.get("url"):
                            parts.append(rtf_paragraph([rtf_run(res["url"], color=4, size=20)], indent=540, space_after=20))
                        if res.get("description"):
                            parts.append(rtf_paragraph([rtf_run(res["description"], color=2, size=20)], indent=540, space_after=60))

                else:
                    content = section.get("content", "")
                    if content:
                        for block in html_to_blocks(content):
                            if block["type"] == "subheading":
                                parts.append(rtf_paragraph([rtf_run(block["text"], bold=True)], space_after=30))
                            elif block["type"] == "paragraph":
                                runs = [rtf_run(text, bold=is_bold) for text, is_bold in block["parts"]]
                                parts.append(rtf_paragraph(runs, space_after=80))
                            elif block["type"] == "list":
                                for item_parts in block["items"]:
                                    runs = [rtf_run("• ")]
                                    runs.extend(rtf_run(text, bold=is_bold) for text, is_bold in item_parts)
                                    parts.append(rtf_paragraph(runs, indent=180, first_indent=-180, space_after=30))

                    for kp in section.get("keyPoints", []):
                        parts.append(rtf_paragraph([rtf_run(f"• {kp}")], indent=180, first_indent=-180, space_after=30))

            if stop_idx < len(tour["stops"]) or tour_idx < len(tours) - 1:
                parts.append(r"\page")

    parts.append("}")
    write_rtf_as_docx("".join(parts), output_path)
    print(f"Document saved to: {output_path}")


# ── Word document builder ────────────────────────────────────────────

def add_rich_paragraph(doc, parts, style="Normal"):
    p = doc.add_paragraph(style=style)
    for text, is_bold in parts:
        run = p.add_run(text)
        run.bold = is_bold
    return p


def add_blocks_to_doc(doc, blocks):
    for block in blocks:
        if block["type"] == "subheading":
            p = doc.add_paragraph(style="Heading 4")
            p.add_run(block["text"])
        elif block["type"] == "paragraph":
            add_rich_paragraph(doc, block["parts"])
        elif block["type"] == "list":
            for item_parts in block["items"]:
                p = doc.add_paragraph(style="List Bullet")
                for text, is_bold in item_parts:
                    run = p.add_run(text)
                    run.bold = is_bold


def render_stop(doc, stop, stop_number):
    """Render a single tour stop into the document."""
    doc.add_heading(f"Stop {stop_number}: {stop['title']}", level=2)

    # Location
    p = doc.add_paragraph()
    loc_run = p.add_run(f"Location: {stop['location']}")
    loc_run.font.italic = True
    loc_run.font.color.rgb = RGBColor(0x55, 0x55, 0x55)

    # Quick facts table
    if stop.get("stats"):
        doc.add_heading("Quick Facts", level=3)
        table = doc.add_table(rows=1, cols=len(stop["stats"]))
        table.alignment = WD_TABLE_ALIGNMENT.LEFT
        hdr = table.rows[0]
        for i, stat in enumerate(stop["stats"]):
            cell = hdr.cells[i]
            p = cell.paragraphs[0]
            label_run = p.add_run(f"{stat['label']}: ")
            label_run.font.size = Pt(10)
            label_run.font.color.rgb = RGBColor(0x55, 0x55, 0x55)
            val_run = p.add_run(stat["value"])
            val_run.bold = True
            val_run.font.size = Pt(11)
        doc.add_paragraph()

    # Sections
    for section in stop.get("sections", []):
        section_type = section.get("type")
        section_label = section.get("label", "")
        section_id = section.get("id", "")

        if section_type == "gallery":
            continue

        # Section heading
        if section_id == "overview":
            doc.add_heading("Overview", level=3)
        elif section_id == "highlights":
            doc.add_heading("At This Stop", level=3)
        elif section_id == "details":
            doc.add_heading(section_label, level=3)
        elif section_type == "resources":
            doc.add_heading("Resources", level=3)
        else:
            doc.add_heading(section_label or section_id.title(), level=3)

        # Render content
        if section_type == "highlights":
            for hi_idx, hi in enumerate(section.get("highlights", []), 1):
                p = doc.add_paragraph()
                num_run = p.add_run(f"{hi_idx}. ")
                num_run.bold = True
                title_run = p.add_run(hi["title"])
                title_run.bold = True
                if hi.get("meta"):
                    meta_run = p.add_run(f"  [{hi['meta']}]")
                    meta_run.font.color.rgb = RGBColor(0x77, 0x77, 0x77)
                    meta_run.font.size = Pt(9)
                desc_p = doc.add_paragraph(hi["description"])
                desc_p.paragraph_format.left_indent = Cm(0.63)

        elif section_type == "resources":
            for res in section.get("resources", []):
                p = doc.add_paragraph(style="List Bullet")
                title_run = p.add_run(res["title"])
                title_run.bold = True
                if res.get("url"):
                    url_run = p.add_run(f"\n{res['url']}")
                    url_run.font.size = Pt(9)
                    url_run.font.color.rgb = RGBColor(0x44, 0x66, 0xAA)
                if res.get("description"):
                    desc_run = p.add_run(f"\n{res['description']}")
                    desc_run.font.size = Pt(10)
                    desc_run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

        else:
            html_content = section.get("content", "")
            if html_content:
                blocks = html_to_blocks(html_content)
                add_blocks_to_doc(doc, blocks)

            key_points = section.get("keyPoints", [])
            if key_points:
                doc.add_paragraph()
                kp_heading = doc.add_paragraph()
                kp_run = kp_heading.add_run("Key Points")
                kp_run.bold = True
                kp_run.font.size = Pt(11)
                for kp in key_points:
                    doc.add_paragraph(kp, style="List Bullet")


def build_document(tours, output_path):
    doc = Document()

    # ── Page setup ───────────────────────────────────────────────────
    section = doc.sections[0]
    section.top_margin = Cm(2.54)
    section.bottom_margin = Cm(2.54)
    section.left_margin = Cm(2.54)
    section.right_margin = Cm(2.54)

    # ── Styles ───────────────────────────────────────────────────────
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(11)
    font.color.rgb = RGBColor(0x33, 0x33, 0x33)
    style.paragraph_format.space_after = Pt(6)
    style.paragraph_format.line_spacing = 1.15

    for level in range(1, 5):
        name = f"Heading {level}"
        if name in doc.styles:
            h = doc.styles[name]
            h.font.name = "Calibri"
            h.font.color.rgb = RGBColor(0x1A, 0x1A, 0x1A)

    # ── Title page ───────────────────────────────────────────────────
    title = doc.add_heading("BSH 2026 Interactive Map Tour", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run("Non-Profit Housing in Vancouver")
    run.font.size = Pt(16)
    run.font.color.rgb = RGBColor(0x55, 0x55, 0x55)

    doc.add_paragraph()

    intro = doc.add_paragraph()
    intro.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = intro.add_run("Tour Content for Editorial Review")
    run.font.size = Pt(12)
    run.font.italic = True
    run.font.color.rgb = RGBColor(0x77, 0x77, 0x77)

    doc.add_paragraph()

    # ── Table of Contents ────────────────────────────────────────────
    doc.add_heading("Table of Contents", level=1)

    global_stop_num = 0
    for tour in tours:
        # Tour group heading in TOC
        p = doc.add_paragraph()
        run = p.add_run(tour["title"])
        run.bold = True
        run.font.size = Pt(11)
        if tour.get("description"):
            desc_run = p.add_run(f"\n{tour['description']}")
            desc_run.font.size = Pt(10)
            desc_run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)
            desc_run.font.italic = True

        for stop in tour["stops"]:
            global_stop_num += 1
            p = doc.add_paragraph(style="List Number")
            run = p.add_run(stop["title"])
            run.font.size = Pt(11)
            location_run = p.add_run(f"  \u2014  {stop['location']}")
            location_run.font.size = Pt(10)
            location_run.font.color.rgb = RGBColor(0x77, 0x77, 0x77)

    doc.add_page_break()

    # ── Tour content ─────────────────────────────────────────────────
    for tour_idx, tour in enumerate(tours):
        # Tour section title
        doc.add_heading(tour["title"], level=1)
        if tour.get("description"):
            p = doc.add_paragraph()
            run = p.add_run(tour["description"])
            run.font.italic = True
            run.font.color.rgb = RGBColor(0x55, 0x55, 0x55)

        doc.add_paragraph()

        for stop_idx, stop in enumerate(tour["stops"]):
            render_stop(doc, stop, stop_idx + 1)

            # Page break between stops
            if stop_idx < len(tour["stops"]) - 1:
                doc.add_page_break()

        # Page break between tours
        if tour_idx < len(tours) - 1:
            doc.add_page_break()

    # ── Save ─────────────────────────────────────────────────────────
    doc.save(output_path)
    print(f"Document saved to: {output_path}")


# ── Main ─────────────────────────────────────────────────────────────

if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    json_path = os.path.join(script_dir, "tour_data.json")
    output_path = os.path.join(script_dir, "BSH_2026_Tour_Content.docx")

    with open(json_path, "r", encoding="utf-8") as f:
        tours = json.load(f)

    total_stops = sum(len(t["stops"]) for t in tours)
    print(f"Loaded {len(tours)} tours with {total_stops} total stops")
    if HAVE_DOCX:
        build_document(tours, output_path)
    else:
        print("python-docx not available; using RTF/textutil fallback")
        build_document_rtf(tours, output_path)
    print("Done! The document is ready for track-changes editing.")
